### PR TITLE
Template for `stack new` command

### PR DESCRIPTION
**Pull request by sandwwraith**
Motivation:

* Templates can insert real user name and email

* Common workflow with `stack` command

* No need to clone the entire repo; can easily do `git init` after creating a project from the template

### CODE REVIEW

**Comment by sandwwraith** [comment]
Maybe it has sense to put `.stylish-haskell.yaml` in the template, too

**Comment by ChShersh** [comment]
@sandwwraith If you want to create full-featured Haskell project with all fields filled with correct values, making project a git repo and creating automatically github remote repository with Travis enabled, you can look for this project:

https://github.com/vrom911/hs-init

This repository is not about stack template. With `stack new` command you **CAN'T** create project offline. Several students already had issues with `stack`. This repository is intended to be used as just `git clone` once and then you can modify project structure and use this template. Also, with `stack new` (without template) you can't create multipackage projects. Personally, I think that structuring all homeworks as a single multipackage project is convenient. This template provides example of such configuration.

Having stack template is really nice though! You can create your own repo with stack template which emulates current repository and I will add your template to our course if you write good README.

**Comment by sandwwraith** [comment]
Hello, thanks for the feedback!

It's a really nice project you're supposing, but it doesn't provide any ways to configure or predefine another project structure, what we both are trying to achieve.

Offline work is really hard task, though, and `git clone` would not work in such conditions either.

Template, which I propose, is completely duplicating your multipackage project structure, and there will be no problems with modifying project structure when project is already created. 

I understood that you've created this repository only for `git clone` purpose, so I'm closing this PR now. I want to improve homework experience, and if some other people would find that using templating is more convenient for them, I hope they can use my template. I suggest to put another link on course homepage directly to my fork of this repo, after I update my README.

**Comment by sandwwraith** [comment]
Hello, thanks for the feedback!

It's a really nice project you're supposing, but it doesn't provide any ways to configure or predefine another project structure, what we both are trying to achieve.

Offline work is really hard task, though, and `git clone` would not work in such conditions either.

Template, which I propose, is completely duplicating your multipackage project structure, and there will be no problems with modifying project structure when project is already created. 

I understood that you've created this repository only for `git clone` purpose, so I'm closing this PR now. I want to improve homework experience, and if some other people would find that using templating is more convenient for them, I hope they can use my template. I suggest to put another link on course homepage directly to my fork of this repo, after I update my README.

**Comment by ChShersh** [comment]
> It's a really nice project you're supposing, but it doesn't provide any ways to configure or predefine another project structure, what we both are trying to achieve.

This project is relatively new and under development. You can try to improve it and your work will be rewarded in our course.

> Offline work is really hard task, though, and git clone would not work in such conditions either.

It's not hard task. The only thing `stack` needs to do online is to check date of latest resolver. `git clone` doesn't achieve goal of full offline work. But with some internet providers `git clone` works while `stack new` doesn't work.

> Template, which I propose, is completely duplicating your multipackage project structure

On the other hand it's convenient to have template in the repo itself because it's easier to modify template when project structure will be modified. The only advantages of template I see is an ability to specify author name and other fields. But those fields are not important for homework.

> I suggest to put another link on course homepage directly to my fork of this repo, after I update my README.

That's can be done.

**Pull request merged**
